name: NutriNova - Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install Dependencies
        working-directory: termProject
        run:  npm install
      
      - name: Build
        working-directory: termProject
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: termProject/dist